<template>
  <div class="card-box">
    <!-- 写死的table表格 -->
    <!-- <div class="table" style="margin-top: 10px">
      <SaleSummaryTable
        :directName="c"
        :mesInfo="innerTableList"
        :color="color"
        @handleClick="namesClick"
      />
      <SaleSummaryTable
        :directName="directName2"
        :mesInfo="outerTableList"
        :color="color2"
        @handleClick="namesClick"
      />
    </div> -->
    <div
      class="table"
      style="margin-top: 10px"
      v-if="
        $store.state.currentPath === 's' ||
        $store.state.currentPath === 'exprotProductCo' ||
        $store.state.currentPath === 'domesticProductCoOffline' ||
        $store.state.currentPath === 'productCoAll' ||
        $store.state.currentPath === 'productCo' ||
        $store.state.currentPath === 'domesticProductCoOnline'
      "
    >
      <RowTable
        :color="color"
        :title="directName"
        :mesInfo="innerTableList"
        :titleHead="titleHead"
        :directName="directName"
        :rowSpanNumber="rowSpanNumber1"
        @handleClick="namesClick"
        :setTrueOrFalse="setTrueOrFalse"
        :cooprMode="cooprMode"
      />
      <RowTable
        :color="color2"
        :title="directName2"
        :mesInfo="outerTableList"
        :titleHead="titleHead"
        :directName="directName2"
        :rowSpanNumber="rowSpanNumber2"
        @handleClick="managerClick"
        :setTrueOrFalse="setTrueOrFalse"
        :cooprMode="cooprMode"
      />
    </div>
    <div
      class="table"
      style="margin-top: 10px"
      v-if="
        $store.state.currentPath === 'domesticSalesOnline' ||
        $store.state.currentPath === 'domesticOnLinePlatform' ||
        $store.state.currentPath === 'domesticOnLineShop' ||
        $store.state.currentPath === 'domesticOnLineSales' ||
        $store.state.currentPath === 'exprotAreaAll' ||
        $store.state.currentPath === 'domestic' ||
        $store.state.currentPath === 'domesticOnLine' ||
        $store.state.currentPath === 'domesticOffLine' ||
        $store.state.currentPath === 'exprot' ||
        $store.state.currentPath === 'exprotSales' ||
        $store.state.currentPath === 'exprotArea' ||
        $store.state.currentPath === 'domesticOffLineSales' ||
        $store.state.currentPath === 'domesticOffLinePlaceCo' ||
        $store.state.currentPath === 'domesticOffLineChannel' ||
        $store.state.currentPath === 'domesticOffLinePlace' ||
        $store.state.currentPath === 'domesticOnLineShopCo' ||
        $store.state.currentPath === 'exprotSalesProductCo'
      "
    >
      <SellSportTable
        :mesInfo="innerTableList"
        :title="directName"
        :color="color"
        @handleClick="namesClick"
      />
      <SellSportTable
        :mesInfo="outerTableList"
        :title="directName2"
        :color="color2"
        @handleClick="managerClick"
      />
    </div>
  </div>
</template>
<script>
import SaleSummaryTable from "@/views/componets/table/SaleSummaryTable.vue";
import SellSportTable from "@/views/componets/table/SellSportTable.vue";
import RowTable from "@/views/componets/table/RowTable.vue";
import { useStore } from "vuex";
import { reactive, toRefs, computed, watch, compile } from "vue";
import { useRouter } from "vue-router";
export default {
  components: {
    SaleSummaryTable,
    SellSportTable,
    RowTable,
  },
  data() {
    return {
      color: "linear-gradient(to right , #50C0FF,#5AFFA3,#66FFFF) ",
      color2: "linear-gradient(to right , #1B6FFF, #7A5AFF, #7066FF) ",
    };
  },
  setup() {
    const Store = useStore();
    const Route = useRouter();
    const data = reactive({
      rowSpanNumber1: 3,
      rowSpanNumber2: 6,
      // directName: computed(() => Store.state.tableOneHeading),
      // directName2: computed(() => Store.state.tableTwoHeading),
      cooprMode: "渠道",
      directName: "内销",
      directName2: "外销",
      setTrueOrFalse: true,
      innerTableList: computed(() => Store.state.tableList.innerDirect),
      outerTableList: computed(() => Store.state.tableList.outerDirect),
      titleHead: computed(() => Store.state.tableList.title),
      tableList: {
        innerDirect: [
          {
            directName: "内销",
            marketChannel: "线上",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "京东",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 22,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线上",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "淘系",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 23,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线上",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "拼多多",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线下",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "分中心",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线下",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "下沉",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线下",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "新渠道",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "合计",
            cooprMode: "",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "外销",
            marketChannel: "大区",
            marketCenter: null,
            manager: null,
            cooprMode: "北美",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "亚太",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "中东非",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "日本",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "韩国",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "拉美",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "合计",
            cooprMode: "拉美",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
        ],
        title: {
          businessEntityName1: "环境",
          businessEntityName2: "烹饪",
          businessEntityName3: "电磁",
          businessEntityName4: "调理",
          businessEntityName5: "电动",
          businessEntityName6: "饮品",
        },
      },
      demosticDirectOnOnline: {
        title: {
          manager: "责任人",
          saleTaskAmt: "责任制",
          businessEntityName1: "累计达成",
          businessEntityName2: "任务完成率",
          businessEntityName3: "毛利率",
          businessEntityName4: "周转天数",
          businessEntityName5: "说到做到",
          businessEntityName6: "排名",
        },
        innerDirect: [
          {
            directName: "线上",
            marketChannel: "京东",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 22,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "淘系",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "拼多多",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "美的平台",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "兴趣电商",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "天猫",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "线下",
            marketChannel: "型号1",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "型号2",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "型号3",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            ProfitRadio: 22,
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "型号4",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "型号5",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            ProfitRadio: 22,
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "型号6",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            ProfitRadio: 22,
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
      },
      demosticDirectOnOnlineGuest: {
        title: {
          manager: "责任人",
          saleTaskAmt: "责任制",
          businessEntityName1: "累计达成",
          businessEntityName2: "任务完成率",
          businessEntityName3: "毛利率",
          businessEntityName4: "周转天数",
          businessEntityName5: "说到做到",
          businessEntityName6: "排名",
        },
        innerDirect: [
          {
            directName: "线上",
            marketChannel: "京东",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 22,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "淘系",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "拼多多",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "美的平台",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "兴趣电商",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "天猫",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "线上",
            marketChannel: "京东",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 22,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "淘系",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "拼多多",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "美的平台",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "兴趣电商",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "天猫",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
      },
      demosticDirectOnOnlineShop: {
        title: {
          manager: "责任人",
          managerSystem: "责任制",
          businessEntityName1: "累计达成",
          businessEntityName2: "任务完成率",
          businessEntityName3: "毛利率",
          businessEntityName4: "周转天数",
          businessEntityName5: "说到做到",
          businessEntityName6: "排名",
        },
        innerDirect: [
          {
            directName: "线下",
            marketChannel: "破壁机",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "豆浆机",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "绞肉机",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "洗衣机",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            ProfitRadio: 22,
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "吹风机",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            ProfitRadio: 22,
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            ProfitRadio: 22,
            marketChannel: "其他",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "内销",
            ProfitRadio: 22,
            marketChannel: "合计",
            marketCenter: null,
            manager: "张茉欧",
            managerSystem: "199",
            businessEntityName1: 199,
            businessEntityName2: 199,
            businessEntityName3: 199,
            businessEntityName4: 199,
            businessEntityName5: 199,
            businessEntityName6: null,
            saleVolume2: 30,
            saleVolume5: 30,
            completeRadioAll: null,
            cnyAmt: 2770085.0577,
            saleTaskAmt: 18,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "线下",
            ProfitRadio: 22,
            marketChannel: "型号1",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            ProfitRadio: 22,
            marketChannel: "型号2",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            ProfitRadio: 22,
            marketChannel: "型号3",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            ProfitRadio: 22,
            marketChannel: "型号4",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            ProfitRadio: 22,
            marketChannel: "型号5",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "其他",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            ProfitRadio: 22,
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
      },
      offlineDetail: {
        title: {
          manager: "责任人",
          managerSystem: "责任制",
          businessEntityName1: "累计达成",
          businessEntityName2: "任务完成率",
          businessEntityName3: "毛利率",
          businessEntityName4: "周转天数",
          businessEntityName5: "说到做到",
          businessEntityName6: "排名",
        },
        innerDirect: [
          {
            directName: "线下",
            marketChannel: "苏宁",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            ProfitRadio: 22,
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "天猫",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            ProfitRadio: 22,
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "淘宝",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "拼多多",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "分中心",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "其他",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "线下",
            marketChannel: "客户1",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "客户2",
            marketCenter: null,
            ProfitRadio: 22,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "客户3",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "客户4",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "客户5",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "其他",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
      },
      placeArea: {
        title: {
          manager: "责任人",
          managerSystem: "责任制",
          businessEntityName1: "累计达成",
          businessEntityName2: "任务完成率",
          businessEntityName3: "毛利率",
          businessEntityName4: "周转天数",
          businessEntityName5: "说到做到",
          businessEntityName6: "排名",
        },
        innerDirect: [
          {
            directName: "线下",
            marketChannel: "中东非",
            marketCenter: null,
            ProfitRadio: 22,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "日本",
            marketCenter: null,
            ProfitRadio: 22,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "韩国",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "西北欧",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "北美",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "亚太",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "合计",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "线下",
            marketChannel: "北美",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "亚太",
            marketCenter: null,
            ProfitRadio: 22,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "日本",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "韩国",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "亚太",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "西北欧",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
      },
      southAmerciaData: {
        title: {
          manager: "责任人",
          managerSystem: "责任制",
          businessEntityName1: "累计达成",
          businessEntityName2: "任务完成率",
          businessEntityName3: "毛利率",
          businessEntityName4: "周转天数",
          businessEntityName5: "说到做到",
          businessEntityName6: "排名",
        },
        innerDirect: [
          {
            directName: "线下",
            marketChannel: "巴西",
            marketCenter: null,
            ProfitRadio: 22,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "阿根廷",
            marketCenter: null,
            ProfitRadio: 22,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "哥伦比亚",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "智利",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "美国",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "墨西哥",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "合计",
            marketCenter: null,
            ProfitRadio: 22,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "线下",
            marketChannel: "巴西",
            marketCenter: null,
            ProfitRadio: 22,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "阿根廷",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "哥伦比亚",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "智利",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "美国",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            ProfitRadio: 22,
            marketChannel: "墨西哥",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
      },
      categoryData: {
        innerDirect: [
          {
            directName: "内销",
            marketChannel: "线上",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "台扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 22,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线上",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "循环扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 23,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线上",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "无叶风扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线下",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "空净品类",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线下",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "挂烫机",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线下",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "塔扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "合计",
            cooprMode: "",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "外销",
            marketChannel: "大区",
            marketCenter: null,
            manager: null,
            cooprMode: "台扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "循环扇",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "无叶风扇",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "空净品类",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "挂烫机",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "塔扇",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "合计",
            cooprMode: "拉美",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
        ],
        title: {
          businessEntityName1: "环境",
          businessEntityName2: "烹饪",
          businessEntityName3: "电磁",
          businessEntityName4: "调理",
          businessEntityName5: "电动",
          businessEntityName6: "饮品",
        },
      },
      outlineComp: {
        innerDirect: [
          {
            directName: "内销",
            marketChannel: "北美KA",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "台扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 22,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "亚太",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "循环扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 23,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "中东非",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "无叶风扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "日本",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "空净品类",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "韩国",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "挂烫机",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "西北欧",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "塔扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "合计",
            cooprMode: "",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "外销",
            marketChannel: "北美KA",
            marketCenter: null,
            manager: null,
            cooprMode: "台扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "亚太",
            cooprMode: "循环扇",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "中东非",
            cooprMode: "无叶风扇",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "日本",
            cooprMode: "空净品类",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "韩国",
            cooprMode: "挂烫机",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "西北欧",
            cooprMode: "塔扇",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "合计",
            cooprMode: "拉美",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
        ],
        title: {
          businessEntityName1: "环境",
          businessEntityName2: "烹饪",
          businessEntityName3: "电磁",
          businessEntityName4: "调理",
          businessEntityName5: "电动",
          businessEntityName6: "饮品",
        },
      },
    });
    let tableList = reactive({ data: {} });
    tableList.data = computed(() => Store.state.tableList);
    watch(tableList, (newVal, oldVal) => {});
    watch(data.innerTableList, (newVal, oldVal) => {

    },  { immediate: true });
    watch(data.outerTableList, (newVal, oldVal) => {
      // data.outerTableList = ...newVal;
    },  { immediate: true });
    watch(
      () => Route.currentRoute.value.name,
      (newVal, oldVal) => {
        switch (newVal) {
          case "s":
            data.directName = "内销";
            data.directName2 = "外销";
            // console.log(Store.state.tableList, "tableListtableList");
            // Store.commit("setTableList", data.tableList);
            break;
          case "domestic":
            data.directName = "线上";
            data.directName2 = "线下";
            // Store.commit("setTableList", data.demosticDirectOnOnline);
            break;
          case "domesticOnLine":
            data.directName = "通路";
            data.directName2 = "重要客户";
            Store.commit("setTableList", data.demosticDirectOnOnline);
            break;
          case "exprot":
            data.directName = "大区";
            data.directName2 = "区域";
            break;
          case "productCoAll":
            data.cooprMode = "渠道";
            data.directName = "内销";
            data.directName2 = "外销";
            data.setTrueOrFalse = true;
            console.log(
              Store.state.tableList,
              "productCoAll",
              data.setTrueOrFalse
            );
            break;
          case "productCo":
            data.directName = "内销";
            data.directName2 = "外销";
            data.cooprMode = "渠道";
            Store.commit("setTableList", data.categoryData);
            break;
          case "domesticOffLine":
            data.directName = "通路";
            data.directName2 = "重点客户";
            Store.commit("setTableList", data.offlineDetail);
            break;
          case "exprotAreaAll":
            data.directName = "区域";
            data.directName2 = "KA客户";
            break;
          case "exprotProductCo":
            data.directName = "cooprMode";
            data.directName2 = "cooprMode";
            data.cooprMode = "环境";
            data.rowSpanNumber1 = 1;
            data.rowSpanNumber2 = 1;
            break;
          case "domesticOnLineShop":
            data.directName = "品类";
            data.directName2 = "重点型号";
            console.log(Store.state.tableList, "domesticOnLineShop");
            break;
          case "domesticOffLineChannel":
            data.directName = "品类";
            data.directName2 = "重点型号";
            break;
          case "domesticOnLinePlatform":
            data.directName = "通路-自营";
            data.directName2 = "KA";
            Store.commit("setTableList", data.demosticDirectOnOnlineGuest);
            break;
          case "domesticOffLinePlaceCo":
            data.directName = "通路-自营";
            data.directName2 = "KA";
            // Store.commit("setTableList", data.demosticDirectOnOnline);
            break;
          case "exprotArea":
            data.directName = "品类";
            data.directName2 = "重点型号";
            break;
          case "domesticOnLineSales":
            data.directName = "品类";
            data.directName2 = "重点型号";
            break;
          case "domesticOffLineSales":
            data.directName = "品类";
            data.directName2 = "重点型号";
            break;
          case "exprotSales":
            data.directName = "品类";
            data.directName2 = "重点型号";
            break;
          case "domesticOffLine":
            data.directName = "通路";
            data.directName2 = "重点客户";
            console.log(Store.state.tableList);
            break;
          case "domesticProductCoOnline":
            Store.commit("setTableList", data.tableList);
            data.setTrueOrFalse - false;
            break;
          case "domesticProductCoOffline":
            Store.commit("setTableList", data.tableList);
            data.setTrueOrFalse = false;
            break;
          case "exprotAreaAll":
            Store.commit("setTableList", data.southAmerciaData);
            break;
          case "exprotProductCo":
            Store.commit("setTableList", data.outlineComp);
            break;
          case "domesticOnLinePlatform":
            Store.commit("setTableList", data.demosticDirectOnOnlineShop);
            break;
          case "domesticOffLinePlace":
            Store.commit("setTableList", data.outlineComp);
            break;
          case "domesticOnLinePlatformCo":
            Store.commit("setTableList", data.offlineDetail);
            break;
          case "exprotArea":
            Store.commit("setTableList", data.demosticDirectOnOnline);
            break;
          case "exprotAreaProductCo":
            Store.commit("setTableList", data.exprotAreaProductCo);
            data.setTrueOrFalse = false;
            break;
          case "domesticOnLineShop":
            Store.commit("setTableList", data.demosticDirectOnOnlineShop);
            break;
          case "domesticOffLineChannel":
            Store.commit("setTableList", data.demosticDirectOnOnlineShop);
            break;
          case "domesticOnLineSales":
            Store.commit("setTableList", data.demosticDirectOnOnlineShop);
            break;
          case "domesticOffLineSales":
            Store.commit("setTableList", data.demosticDirectOnOnlineShop);
            break;
          case "exprotSales":
            Store.commit("setTableList", data.demosticDirectOnOnlineShop);
            break;
          case "domesticOnLineShopCo":
            // Store.commit("setTableList", data.demosticDirectOnOnlineShop);
            data.directName = "品类";
            data.directName2 = "重点型号";
            console.log(
              Store.state.tableList,
              "domesticOnLineShopCodomesticOnLineShopCo"
            );
            break;
          case "exprotSalesProductCo":
            Store.commit("setTableList", data.demosticDirectOnOnlineShop);
            data.directName = "品类";
            data.directName2 = "重点型号";
            break;
          case "exprotSales":
            Store.commit("setTableList", daata.demosticDirectOnOnlineShop);
            data.directName = "品类";
            data.directName2 = "重点型号";
          default:
            break;
        }
      },
      { immediate: true }
    );
    let namesClick = () => {
      switch (Store.state.currentPath) {
        case "s":
          Route.push("domesticOnLinePlatform");
          break;
        case "domestic":
          Route.push("domesticOnLineShop");
          break;
        case "domesticOnLinePlatform":
          Route.push("domesticOnLineShop");
          break;
        case "domesticOnLineShop":
          Route.push("domesticOnLineSales");
          break;
        case "domesticOnLine":
          Route.push("domesticOnLineShop");
          break;
        case "domesticOnLine":
          Route.push("domesticOnLineSales");
          break;
        case "domesticOffLine":
          Route.push("domesticOffLineChannel");
          break;
        case "exprot":
          Route.push("exprotArea");
          break;
        case "exprotAll":
          Route.push("exprotArea");
          break;
        case "exprotAreaAll":
          Route.push("exprotArea");
          break;
        case "exprotArea":
          Route.push("exprotSales");
        case "domesticOffLinePlaceCo":
          // Route.push("domesticOffLineChannel");
          break;
        case "domesticOffLineChannel":
          Route.push("domesticOffLineSales");
          break;
        case "exprotSalesProductCo":
          Route.push("exprotSales");
        default:
          break;
      }
      // 获取level，记录当l前虚拟网页的名称到Vuex,调接口重新获取数据后刷新页面
    };
    let managerClick = () => {
      switch (Store.state.currentPath) {
        case "s":
          // Store.commit("setTableList", ...data.demosticDirectOnOnline);
          Route.push("exprotAreaAll");
          break;
      }
    };
    let switchCurrentPath = () => {
      switch (Store.currentPath) {
        case "s":
          data.directName = "小区";
          data.directName2 = "大区";
          return true;
          break;
        case "domestic":
          data.directName = "线上";
          data.directName2 = "线下";
          return false;
        default:
          break;
      }
    };
    return {
      switchCurrentPath,
      managerClick,
      namesClick,
      ...toRefs(data),
    };
  },
};
</script>
<style scoped>
.table {
  width: 1840px;
  height: 330px;
  display: flex;
  justify-content: space-between;
  margin: 0 auto;
}
</style>
